### ISSUE TITLE
Unexpected results from the AUR [citip-git]

### ISSUE THREAD

**Issue by coldfix** [jjk-jacky/kalu#28]
Hey,

when checking for upgrades, I get the following message: "Unexpected results from the AUR [citip-git]".

Interestingly, this is a package which I just uploaded a few days ago. I'm not sure whats wrong with it. Do you get the same error or does this issue only exist for me? Hope, this doesn't affect others.

Best regards,
Thomas

**Comment by jjk-jacky** [comment]
Seems to work fine here. Looking how that error might occur, this
basically happens when the package name from the AUR doesn't match what
kalu was expecting.

For instance, if I add "citip-git" to my watched AUR packages,
everything works fine. However, if I add "Citip-git" then I get the same
error; This is because it seems the AUR is case insensitive, but kalu
does case-sensitive comparisons, hence the mismatch/failure.

So if you've added this to your watched AUR packages, check that it's
all in lowercase, also that you don't have a space as first/last character.
If that's not the issue, try running `kalu -dd` from a terminal and
check the output, there might be a clue as to what's causing this.

**Comment by coldfix** [comment]
Thanks! I didn't have it in my watchlist, but did install it using a previous version of the PKGBUILD where the initial C was still uppercase.
Sorry for bothering.
