### ISSUE TITLE
Add autostart option

### ISSUE THREAD

**Issue by bosyi** [jjk-jacky/kalu#30]

**Comment by jjk-jacky** [comment]
Not sure what you mean by that, care to elaborate?

**Comment by bosyi** [comment]
Just add a gui (in preferences) option to (auto)start at login. Thanks!
![2015-06-12 15-20-57](https://cloud.githubusercontent.com/assets/1587322/8129944/32979a50-1117-11e5-87c8-1db56eb301ab.png)

**Comment by jjk-jacky** [comment]
Oh, I see. Sorry, but I don't think I wanna do that, actually. Because
it doesn't feel like this is how it should be done, plus I'm not sure
there's one single way to get that done, as that may depend on your
setup (e.g. which DE you use, etc).
Feels to me it's better (and simpler) to simply add kalu in whatever you
use to e.g. open your session.
