### ISSUE TITLE
AUR notification template configuration is not intuitive

### ISSUE THREAD

**Issue by hagabaka** [jjk-jacky/kalu#33]
I have over 100 AUR packages needing update, and I'm not going to get that done any time soon, so I want to make the notifications only show a number and not list the package names. When trying to do that, I found the configuration of the template notification not very intuitive. In the configuration dialog there are checkboxes before "Package" and "Separator", and by default they are unchecked.
![kalu-notification-template-unchecked](https://cloud.githubusercontent.com/assets/11416/9321813/4094f912-4539-11e5-8e05-0def60b13dfe.png)
I would have assumed unchecked meant displaying nothing. However this actually means using the defaults shown in the disabled text box. But then why is "Title" checked by default?

![kalu-notification-template-checked](https://cloud.githubusercontent.com/assets/11416/9321814/4098cd26-4539-11e5-911b-364006883a50.png)
After checking the boxes I can change the template parts. However the dialog does not allow me to leave them empty, and the best I can do is to display a space character for every package and every separator.

My suggestions would be:

1. Make it clear what the checkboxes mean, or better yet replace them with "reset to default" buttons. 
2. Allow the templates to be empty.

**Comment by jjk-jacky** [comment]
Alright so first, the checkboxes: this is because, as said in the doc,
the way things work re: templates is that only the one for Upgrades is
required, as all others will fall back to it (except Watched AUR that
falls back to AUR first, then Upgrades if nothing was set there).

So when checked it means you're setting a value for this field, else it
means to fall back. The reason behind all this is that it wasn't thought
that you'd want not to have a value, every single template was meant to
always have 3 values, and the fall back system provides a way to re-use
values easily.

I agree it might not be very intuitive/obvious though. So I've been
thinking of doing some changes here, and replace the checkboxes with a
list to define the "source" to use: default, fallback, or custom.
(Noting that not all fields have a default, or a fall back, but they all
have at least either a default or a fall back.) Hopefully this should
make things clearer. (Added bonus, your custom value can be
saved/remembered even when not using it, which isn't possible currently.)

Then there's another issue you mention: not using a field, or setting it
to nothing/empty string, isn't allowed. This was mostly because I just
didn't really think one you want a notification w/out at least the list
of packages (names), I guess.

Since the notification API only requires a title, not a body, I'm
thinking of adding "none" as source for all fields but titles.

Would that fix your issues?

**Comment by hagabaka** [comment]
Now I understand your system, and that explains why there aren't checkboxes for the "Upgrades" templates. But I still feel like it would be confusing for other users who haven't read the explanation...

Instead of having selection boxes for "default/fallback", I'd prefer buttons that set the template value when you click them, and leave the text box enabled for editing. This makes it easy for users who want to have similar but not identical templates. It also simplifies user mental model and the configuration logic as you have only a template string value, rather than a set of "modes" for setting it, one of which refers to a template string value.

It would be even clearer if all the template settings were on tab, so that when you set a value to "fallback", it's clear what it does. Or in that case you could just do away with the fallback option, because it would be easier to copy and paste directly with them on the same screen. However that might result in a crowded "template" tab and a few other empty tabs.

**Comment by jjk-jacky** [comment]
hmm... I don't like the button solution, because it doesn't really work
well with the falling back system, as in you set a template once and it
is used in more than one places. So you only need to update/maintain it
once, and it applies to all relevant notifications. I really like that,
so this falling back system isn't going anywhere.

The idea to be able to edit things though, to e.g. tweak them a bit, is
a good one however. But I'd simply add a button "import" next to the
text box, so one can import the default/fall back value on demand, and
then edit it as pleased.
But in addition to the source list, to set what is actually used.

(And yeah, I don't think putting all 6 templates in one (very crowded)
tab would look good, nor make things simpler/easier to deal with really.
And again, I wanna keep the falling back system in, so.)

**Comment by hagabaka** [comment]
If you feel strongly about having a "linked" fallback option, don't worry about the import button. I think that would just add to confusion.

Maybe you can use a combo box, instead of replacing the checkbox with a listbox and having a text field along side. The combobox would only have two options, for example "(default) - <b>$PKG</b> $OLD > <b>$NEW</b> (D: $DL; N: $NET)" and "(fallback) - $PKG". Selecting either option would bind the setting to the default or fallback, so if the fallback option changes, that setting would change too. However editing the textbox will break the binding and change it to a custom setting.

**Comment by jjk-jacky** [comment]
Alright, so I thought some more about this, then basically went ahead
with my idea of adding a source list. Here's why: there was actually a
flaw/bug in the preferences window, in that it didn't exactly reflect
how things worked, i.e. what kalu allowed when parsing the conf file.

Specifically, if writing the file manually, you could choose between
using the default (no option set), using the fall back (option set w/out
value), or using a custom value (option set w/ said value).

However, in the Prefs. window it was only fall back or custom, any
default value being treated as a user-supplied custom one.
Additionally, the way this worked to basically store 2 information
within one option wasn't ideal.

So now, every field in a template has two options, with a new *Sce
option that can be DEFAULT, FALLBACK, CUSTOM or NONE, making the whole
thing clearer (and having the same in Prefs. window).

Actually, titles can only have DEFAULT or CUSTOM: they don't have fall
backs anymore (since it never really made sense for them anyways),
always have a default value (already did, for the same reason), and are
required.

Every other field however has either a default or a fall back, or both.
Using one when not applicable (e.g. using DEFAULT when there's none)
will simply have kalu silently switch to the other (e.g. FALLBACK).
And they can also be set to NONE (for Package it'll mean the
notification is only a title).

All this is now properly reflected on Prefs. window, where default and
fall back values are shown in read-only mode, with a button in the entry
to edit them as custom value.

I've pushed all this to a new branch templates, please give it a try and
let me know how that works for you. (Note that I haven't updated the doc
yet.)

Cheers,
-j

**Comment by hagabaka** [comment]
It works well. Maybe add tooltips on the "fallback/custom/none" box to explain what the options mean, particularly "fallback". If it's possible to use an empty string as a custom value I would prefer that, otherwise when selecting None, the text box should be disabled.

**Comment by jjk-jacky** [comment]
Yep, good ideas, done both; pushed in templates.
Thanks.
