### ISSUE TITLE
Add tracking of system upgrade without kalu gui

### ISSUE THREAD

**Issue by bosyi** [jjk-jacky/kalu#34]
Add tracking of pacman.log? to see if system were updated without kalu gui.

**Comment by jjk-jacky** [comment]
Not sure what you're looking for, but there's no need to track anything
-- Just re-run the checks and you'll get an up-to-date situation, you
always do, regardless of what frontend was used to update the system.

**Comment by bosyi** [comment]
-- Just re-run the checks
Can it be done automatically?

Case:
Kalu notifies me about new updates. Kalu icon becomes blue. I run in terminal 'pacman -Syu' -> system updated. Kalu icon still blue, but system just updated.

I wish kalu somehow track that. What do you think about that?

**Comment by jjk-jacky** [comment]
> -- Just re-run the checks
> Can it be done automatically?

Not really. I mean there's no real way to track that.

A simpler solution would be for you to re-run the checks. If you use
kalu to start a terminal emulator w/ `pacman -Syu` in it (instead of
using kalu's updater that is) it's done automatically, or you could use
a script/alias instead of running pacman manually, that would simply
send "auto-checks" to kalu on its FIFO (see man page for more)

E.g: pacman -Syu; echo auto-checks > $XDG_RUNTIME_DIR/kalu_fifo_*
