### ISSUE TITLE
Arch Linux security alerts Notifications

### ISSUE THREAD

**Issue by efgee** [jjk-jacky/kalu#40]
Hello,
Using kalu and like it very much.

One thing that I would really like is adding Arch Linux security alerts notification.
One site that publishes them is: http://lwn.net/Alerts/Arch_Linux/

It would be awesome if this could be implemented.
Thank you for providing this gem to Arch users.

**Comment by jjk-jacky** [comment]
I'm afraid that's not really possible, and a bit outside kalu's scope
really. If you don't wanna miss those alerts, subscribing to the
mailing list is the right way to do so.

(If you really want those in kalu, you'd have to find an RSS feed
providing those, and use it instead of the Arch Linux News feed.)
