### ISSUE TITLE
Set notifications as 'transient'

### ISSUE THREAD

**Issue by stenrose** [jjk-jacky/kalu#55]
Notifications from kalu isn't transient, so when leaving the desktop for a few hours the notifications is stacked in the notification tray (or similar).

It would be handy if the notifications was set as `transient` (I'm not sure if that's actually the correct term) so only the latest notification is "saved". The notification applet with Cinnamon, for example, supports [destroying transient notifications](https://github.com/linuxmint/Cinnamon/pull/2646).

What's your opinion?

**Comment by jjk-jacky** [comment]
Ah, yes this seems like a better solution to deal with "persistent
notifications" than the NotifButtons config tweak. (Although it seems
to me that all those servers are bugged, since they don't honor the
expiration timeout...)

This could be added as another config tweak yes. Not sure I have much
time to work on this ATM, but patches welcome :)

**Comment by stenrose** [comment]
@jjk-jacky, is it possible to (perhaps with kalu.conf) to disable notifications with kalu? Thus, only relying on the kalu systray icon turning blue when updates are available? That would be a reasonable workaround for myself.

**Comment by jjk-jacky** [comment]
Yes, if you check the help/man page you'll see there's a config tweak to
disable notifications for automatic checks; That might be what you're
looking for.
