### ISSUE TITLE
Kalu falsely identifying unread news

### ISSUE THREAD

**Issue by protist** [jjk-jacky/kalu#58]
Kalu notified me a couple of days ago of 10 unread news items. I had previously marked them all as read. I marked them all as read again, and then today was informed the same 10 news items were unread.

If no one else has seen this problem, is there something corrupt in my config I could look at?

Up-to-date Arch
kalu-kde 4.1.0-2

**Comment by jjk-jacky** [comment]
Nothing corrupt in your config no, I believe this is the same issue as
#56, so a bug which should be fixed in branch next.

Probably would be a good idea to have a new release soon-ish, if I
can find time, but in the mean time you can either compile from branch
next or import the fix, and the problem should go just away.

**Comment by protist** [comment]
Great, thanks for the tip; I'll test it out and report back in a few days.

**Comment by yan12125** [comment]
I got the same issues and replacing aur/kalu with aur/kalu-git (which builds from ```next``` branch) and everything works as usual. Thanks for the awesome work @jjk-jacky!

**Comment by protist** [comment]
@jjk-jacky I haven't had any false positives in the last two days since patching kalu-kde, so I'll mark this as solved. Thanks again for the quick fix!
