### ISSUE TITLE
% download doesn't be shown right

### ISSUE THREAD

**Issue by rplanchuelo** [jjk-jacky/kalu#63]
is it possible that it is because of regional configuration (decimal point)

![kalu_download](https://user-images.githubusercontent.com/32977921/40842289-ae051788-65ad-11e8-9276-334b35d2874a.png)

**Comment by jjk-jacky** [comment]
No, I believe this is because you built kalu against pacman 5.1, but it
isn't compatible with it. (Note: there's a reason the AUR package has a
dependency on pacman<5.1)

If you wanna build kalu against pacman 5.1 use the pacman-5.1 branch,
which has compatibility changes, or wait a new release is done, which
should happen in the coming days hopefully.
