### ISSUE TITLE
Feature request: notifying when an installed watched package is stale

### ISSUE THREAD

**Issue by infokiller** [jjk-jacky/kalu#65]
Thanks for making Kalu!

I would like to be able to specify a set of packages and get a notification when they are updated. I know that I can specify watched packages, but then I also need to specify a version, and when the package gets updated I also need to update the version in the watched packages file.
Is there a way for me to achieve what I want?

**Comment by jjk-jacky** [comment]
I feel like what you're after is really the watched packages feature.
Are you using kalu as a CLI-only tool ? In that case indeed you need to
update the version number, since there is no interface of any kind.

On the other hand if you're using the GUI, you don't need to do it
manually: from the notification there's an action button that will list
all the watched packages with a new version available, you can there
check those to update and validate. kalu will then update all the
version numbers accordingly, so you don't actually need to keep track
of/update them yourself; It's (part of) the whole idea.
Same goes for watched AUR packages of course.

(In fact, when adding new watched packages you don't even have to care
about the version number: just add it/them into the list without a
version number, so it'll default to zero (0). Then run the checks, and
use the list as described above to have all version numbers set
properly. That way you're sure not to get one wrong or anything.)

**Comment by infokiller** [comment]
You're right, sorry, I just realized that the notifications from Kalu had action buttons that I missed because I'm using Dunst.
